name: GitHub Actions
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch on Push and any branches on PR
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: node --version
      - run: npm --version

      - name: Install npm/yarn dependencies
        run: |
          cd bootstrap5-i18n-demo
          yarn install

      - name: Prod Build for GitHub demo website
        run: |
          cd bootstrap5-i18n-demo
          yarn build

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./bootstrap5-i18n-demo/dist
